services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: php8.1
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./coverage:/opt/phpstorm-coverage
    ports:
      - "9000:9000"
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
