<?php

namespace Onepix\EAvtovokzalApiClient\Enum;

enum DocumentTypeEnum: string
{
    case BIRTH_CERT = 'TYPE_BIRTH_CERT';
    case CERT_LOSS = 'TYPE_CERT_LOSS';
    case MILITARY_ID = 'TYPE_MILITARY_ID';
    case PASSPORT_DIPLOMATIC = 'TYPE_PASSPORT_DIPLOMATIC';
    case PASSPORT_FOREIGN = 'TYPE_PASSPORT_FOREIGN';
    case PASSPORT_INTERNATIONAL = 'TYPE_PASSPORT_INTERNATIONAL';
    case PASSPORT_RUS = 'TYPE_PASSPORT_RUS';
    case PASSPORT_USSR = 'TYPE_PASSPORT_USSR';
    case RESIDENCE = 'TYPE_RESIDENCE';
    case SERVICEMAN_ID = 'TYPE_SERVICEMAN_ID';
    case TEMPORARY_ID_CARD = 'TYPE_TEMPORARY_ID_CARD';
}
