<?php

namespace Onepix\EAvtovokzalApiClient\Enum;

enum StatusEnum: string
{
    case STATUS_BOOKED = 'STATUS_BOOKED';
    case STATUS_CANCELLED = 'STATUS_CANCELLED';
    case STATUS_CREATED = 'STATUS_CREATED';
    case STATUS_ERROR = 'STATUS_ERROR';
    case STATUS_PARTIALLY_CANCELLED = 'STATUS_PARTIALLY_CANCELLED';
    case STATUS_PARTIALLY_RETURNED = 'STATUS_PARTIALLY_RETURNED';
    case STATUS_RETURNED = 'STATUS_RETURNED';
    case STATUS_SOLD = 'STATUS_SOLD';
}
